name: flutter_demo
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  #http: '>=0.11.3+16'
  #fluro: '^1.3.1'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background.png
    - assets/logo.png
